openapi: 3.0.0
info:
  title: Notification System API
  version: "1.0"
paths:
  /users:
    post:
      summary: Register a new user
      ...
    get:
      summary: List all users
      ...
  /notifications/send:
    post:
      summary: Send a notification
      ...
