openapi: 3.0.0
info:
  title: Multichannel Notification API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                preferred_channel:
                  type: string
                available_channels:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Usuario creado exitosamente
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
  /notifications/send:
    post:
      summary: Enviar una notificación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                message:
                  type: string
                priority:
                  type: string
      responses:
        '200':
          description: Notificación procesada
